-- ============================================================
-- ROUTINES
--
-- Stores recurring classes taught by teachers at institutions.
--
-- The academic fields are intentionally flexible because the
-- system supports schools, +2, bachelor's degrees, etc.
--
-- Examples:
--
-- School:
--   grade_id    = 'grade10'
--   section     = 'A'
--   subject_id  = 'mathematics'
--
-- +2:
--   stream_id   = 'science'
--   batch       = '2082'
--   section     = 'A'
--   subject_id  = 'physics'
--
-- Bachelor's:
--   faculty_id  = 'fohss'
--   program_id  = 'ba'
--   semester_id = 'semester3'
--   batch       = '2082'
--   section     = 'A'
--   subject_id  = 'sociology'
-- ============================================================

create table public.routines (
  -- Numeric ID.
  --
  -- This is intentionally not generated by the database because
  -- routines may be created while the app is offline.
  --
  -- The application is responsible for generating a globally
  -- unique ID before synchronization.
  id bigint primary key,

  -- Institution where this routine takes place.
  institution_id uuid not null
    references public.institutions(id)
    on delete cascade,

  -- Teacher who teaches this routine.
  teacher_id uuid not null
    references public.profiles(id)
    on delete cascade,


  -- ==========================================================
  -- ACADEMIC STRUCTURE
  -- ==========================================================

  -- Faculty / institute.
  -- Examples: FoHSS, IoE, IoM
  faculty_id text,

  -- +2 stream.
  -- Examples: Science, Management, Law
  stream_id text,

  -- Degree / program.
  -- Examples: BCA, BA, BE
  program_id text,

  -- School grade.
  -- Examples: KG, 1, 10, 11
  grade_id text,

  -- Semester / term.
  semester_id text,

  -- Institution-specific batch.
  -- Kept as text because batch identifiers may not always
  -- be purely numeric.
  batch text,

  -- Institution-specific section.
  -- Examples: A, B, C
  section text,

  -- Standardized subject identifier from the application's
  -- subject catalog.
  subject_id text not null,


  -- ==========================================================
  -- CLASS TIME
  -- ==========================================================

  start_time time not null,
  end_time time not null,

  -- Days on which the routine occurs.
  --
  -- Example:
  -- {'monday', 'wednesday', 'friday'}
  days text[] not null,


  -- ==========================================================
  -- SYNC METADATA
  -- ==========================================================

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,


  -- ==========================================================
  -- VALIDATION
  -- ==========================================================

  -- A routine cannot end before it starts.
  check (
    end_time > start_time
  ),

  -- A routine must have at least one day.
  check (
    cardinality(days) > 0
  ),

  -- Only valid days are permitted.
  check (
    days <@ array[
      'monday',
      'tuesday',
      'wednesday',
      'thursday',
      'friday',
      'saturday',
      'sunday'
    ]::text[]
  )
);


-- ============================================================
-- INDEXES
-- ============================================================

create index routines_teacher_id_idx
on public.routines(teacher_id);

create index routines_institution_id_idx
on public.routines(institution_id);

create index routines_teacher_institution_idx
on public.routines(
  teacher_id,
  institution_id
);


-- Useful when displaying a teacher's routines ordered by time.
create index routines_teacher_time_idx
on public.routines(
  teacher_id,
  start_time
);


-- ============================================================
-- RLS
-- ============================================================

alter table public.routines enable row level security;


-- ============================================================
-- READ OWN ROUTINES
-- ============================================================

create policy "Teachers can read their own routines"
on public.routines
for select
to authenticated
using (
  auth.uid() = teacher_id
);


-- ============================================================
-- CREATE OWN ROUTINES
-- ============================================================

create policy "Teachers can create their own routines"
on public.routines
for insert
to authenticated
with check (
  auth.uid() = teacher_id
);


-- ============================================================
-- UPDATE OWN ROUTINES
-- ============================================================

create policy "Teachers can update their own routines"
on public.routines
for update
to authenticated
using (
  auth.uid() = teacher_id
)
with check (
  auth.uid() = teacher_id
);


-- ============================================================
-- DELETE
--
-- Physical deletion is intentionally not permitted.
--
-- For offline synchronization, set deleted_at instead.
-- ============================================================


-- ============================================================
-- UPDATED_AT
-- ============================================================

create trigger routines_updated_at
before update on public.routines
for each row
execute function public.update_updated_at();
