-- ROUTINES
--
-- Stores recurring classes taught by teachers at institutess.
--
-- The academic fields are intentionally flexible because the
-- system supports schools, +2, bachelor's degrees, etc.
--
-- Examples:
--
-- School:
--   grade_id    = 'grade10'
--   section     = 'A'
--   subject_id  = 'mathematics'
--
-- +2:
--   stream_id   = 'science'
--   batch       = '2082'
--   section     = 'A'
--   subject_id  = 'physics'
--
-- Bachelor's:
--   faculty_id  = 'fohss'
--   program_id  = 'bca'
--   semester_id = 'semester3'
--   batch       = '2082'
--   section     = 'A'
--   subject_id  = 'sociology'

create table public.routines (
  -- Numeric ID.
  --
  -- This is intentionally not generated by the database because
  -- routines may be created while the app is offline.
  --
  -- The application is responsible for generating a globally
  -- unique ID before synchronization.
  id bigint primary key,

  -- Institutes where this routine takes place.
  institute_id uuid not null
    references public.institutes(id)
    on delete cascade,

  unit_id text not null,

  -- Teacher who teaches this routine.
  teacher_id uuid not null
    references public.profiles(id)
    on delete cascade,

  -- +2 stream.
  -- Examples: Science, Management, Law
  stream_id text,

  -- Degree / program.
  -- Examples: BCA, BA, BE
  program_id text,

  -- School grade.
  -- Examples: KG, 1, 10, 11
  grade_id text,

  -- Semester / term.
  semester_id text,

  -- Institute-specific batch.
  -- Kept as text because batch identifiers may not always
  -- be purely numeric.
  batch text not null,

  -- Institutes-specific section.
  -- Examples: A, B, C
  section text,

  -- Standardized subject identifier from the application's
  -- subject catalog.
  subject_id text not null,

  -- CLASS TIME

  start_time time not null,
  end_time time not null,

  -- Days on which the routine occurs.
  --
  -- Example:
  -- {'monday', 'wednesday', 'friday'}
  days text[] not null,

  -- Sync metadata

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  -- A routine cannot end before it starts.
  check (
    end_time > start_time
  ),

  -- A routine must have at least one day.
  check (
    cardinality(days) > 0
  ),

  -- Only valid days are permitted.
  check (
    days <@ array[
      'monday',
      'tuesday',
      'wednesday',
      'thursday',
      'friday',
      'saturday',
      'sunday'
    ]::text[]
  )
);

